In [1]:
import numpy as np
import scipy

In [97]:
z =[0.0, 6.666666666666667, 13.333333333333334, 20.0, 26.666666666666668, 33.333333333333336, 40.0, 46.66666666666667, 53.333333333333336, 60.0, 66.66666666666667, 73.33333333333334, 80.0, 86.66666666666667, 93.33333333333334, 100.0, 106.66666666666667, 113.33333333333334, 120.0, 126.66666666666667, 133.33333333333334, 140.0, 146.66666666666669, 153.33333333333334, 160.0, 166.66666666666669, 173.33333333333334, 180.0, 186.66666666666669, 193.33333333333334, 200.0]
x = [126, 109, 107, 73, 67, 61, 51, 51, 44, 45, 28, 28, 30, 15, 19, 14, 13, 16, 9, 11, 7, 9, 5, 9, 7, 6, 3, 4, 5, 4]
y = np.array([45])

#first step is to create the pdf for each bin, secondly join the quantiles with lower frequencies than 5, ?thirdly check for any values with a lower probability than alpha? 

In [60]:
len(z)

31

In [66]:
print(y)
print(len(x),len(z))

[45]
30 31


In [12]:
ppf

array([0.02      , 0.01750347, 0.01531857, 0.0134064 , 0.01173292,
       0.01026834, 0.00898658, 0.00786481, 0.00688308, 0.00602388,
       0.00527194, 0.00461386, 0.00403793, 0.00353389, 0.00309277,
       0.00270671, 0.00236884, 0.00207314, 0.00181436, 0.00158788,
       0.00138967, 0.0012162 , 0.00106439, 0.00093152, 0.00081524,
       0.00071348, 0.00062442, 0.00054647, 0.00047826, 0.00041856,
       0.00036631])

In [109]:
dist = scipy.stats.expon
orig_ppf = dist.cdf(z, loc=0, scale=50)
orig_ppf = np.diff(np.append(orig_ppf,[1]))

quantiles = []
freq = []
new_val = 0
ppf = []
new_ppf = 0

for i,val in enumerate(x):
    if (val > 5) & (new_val == 0):
        freq.append(val)
        quantiles.append(z[i])
        ppf.append(orig_ppf[i])
        continue
    new_val += val
    new_ppf += orig_ppf[i]
    if new_val > 5:
        freq.append(new_val)
        quantiles.append(z[i])
        ppf.append(new_ppf)
        new_val = 0
        new_ppf = 0
        continue

expected_freq = np.multiply(np.array(ppf),np.sum(freq))
chi_sq = np.sum((freq - expected_freq)**2 / expected_freq)


In [122]:
chi_sq

16.182190523772487

In [120]:
len(orig_ppf)

31

In [121]:
        # k = len(self.emp_n)  
        # observed = np.array(self.emp_n)
        
        # if self.distr == TestDist.NORMAL:
        #     expected = np.diff(scipy.stats.norm.cdf(self.emp_x, loc=mean, scale=np.sqrt(var))) * sum(observed)
        # elif self.distr == TestDist.EXPONENTIAL:
        #     expected = np.diff(scipy.stats.expon.cdf(self.emp_x, loc=0, scale=mean)) * sum(observed)
       
        # if self.dist_f == scipy.stats.norm:
        #     expected_freq = np.diff(self.dist_f.ppf(q=[0,alpha], loc=mean, scale=var**0.5))
        # elif self.dist_f == scipy.stats.expon:  
        #     expected_freq = np.diff(self.dist_f.ppf([0,alpha], loc=0, scale=mean))
        # print('alpha:', alpha, 'mean:', mean, 'var:', var)
        # # if frequencies are below 5 use neighbouring frequencies
        # combined_emp_x = []
        # combined_emp_n = []
        # curr_freq_sum = 0
        # print(list(self.emp_n))

        # print('emp_x', list(self.emp_x))
        # # for x, n in zip(self.emp_x, self.emp_n):
        # #     if curr_freq_sum + n < 5:
        # #         curr_freq_sum += n
        # #     else:
        # #         combined_emp_x.append(x)
        # #         combined_emp_n.append(curr_freq_sum + n)
        # #         curr_freq_sum = 0
        # #     combined_emp_x.append(x)
        # #     combined_emp_n.append(curr_freq_sum + n)
        # #     self.emp_x = combined_emp_x
        # #     self.emp_n = combined_emp_n
        
        # observed_freq = self.emp_n
        # print(expected_freq[0], self.emp_n)
        # chi_sq = np.sum((observed_freq - expected_freq)**2 / expected_freq)
        # print(chi_sq)
        
        # 
        
        # 

[0.0,
 6.666666666666667,
 13.333333333333334,
 20.0,
 26.666666666666668,
 33.333333333333336,
 40.0,
 46.66666666666667,
 53.333333333333336,
 60.0,
 66.66666666666667,
 73.33333333333334,
 80.0,
 86.66666666666667,
 93.33333333333334,
 100.0,
 106.66666666666667,
 113.33333333333334,
 120.0,
 126.66666666666667,
 133.33333333333334,
 140.0,
 146.66666666666669,
 153.33333333333334,
 160.0,
 166.66666666666669,
 173.33333333333334,
 180.0,
 186.66666666666669,
 193.33333333333334,
 200.0]

In [118]:
freq

[126,
 109,
 107,
 73,
 67,
 61,
 51,
 51,
 44,
 45,
 28,
 28,
 30,
 15,
 19,
 14,
 13,
 16,
 9,
 11,
 7,
 9,
 14,
 7,
 6,
 7,
 9]

In [111]:
np.sum(orig_ppf)

1.0

In [112]:
orig_ppf

array([0.12482668, 0.10924498, 0.09560829, 0.08367383, 0.0732291 ,
       0.06408815, 0.05608824, 0.04908693, 0.04295957, 0.03759707,
       0.03290396, 0.02879666, 0.02520207, 0.02205618, 0.01930298,
       0.01689345, 0.0147847 , 0.01293918, 0.01132402, 0.00991048,
       0.00867339, 0.00759072, 0.00664319, 0.00581395, 0.00508821,
       0.00445307, 0.0038972 , 0.00341073, 0.00298498, 0.00261237,
       0.01831564])

In [115]:
1-np.sum(ppf)

0.01831563888873422

In [62]:
np.sum(np.diff(orig_ppf))

-0.01963368722222532

In [92]:
dist = scipy.stats.expon
orig_ppf = dist.cdf(z, loc=0, scale=50)
# orig_ppf = np.append(orig_ppf,[1.0])
# np.sum(np.diff(orig_ppf))

In [94]:
len(np.diff(orig_ppf))

30

In [93]:
len(orig_ppf)

31

In [73]:
val

0.15765389802551844

In [71]:
orig_ppf

array([0.02      , 0.01750347, 0.01531857, 0.0134064 , 0.01173292,
       0.01026834, 0.00898658, 0.00786481, 0.00688308, 0.00602388,
       0.00527194, 0.00461386, 0.00403793, 0.00353389, 0.00309277,
       0.00270671, 0.00236884, 0.00207314, 0.00181436, 0.00158788,
       0.00138967, 0.0012162 , 0.00106439, 0.00093152, 0.00081524,
       0.00071348, 0.00062442, 0.00054647, 0.00047826, 0.00041856,
       0.00036631])